config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#list', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task

  get "tasks/:id", to: "tasks#display", as: :task
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def list
    @tasks = Task.all
  end
  def display
    @task = Task.find(params[:id])
  end
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.save
    redirect_to tasks_path(@tasks)
  end

  def edit
     @task = Task.find(params[:id])
  end

   def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to tasks_path(@tasks)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def tasks_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/display.html.erb
<h2>Task: <%= @task.title %></h2>
<p>Details: <%= @task.details %></p>
<p>Completed? [<%= @task.completed %>]</p>

<%= link_to 'All tasks', tasks_path %>
<%= link_to 'Edit', edit_path %>
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/tasks/edit.html.erb
<div>
  <%= form_for(@task) do |t| %>
    <p><%= t.label :title %></p>
    <p><%= t.text_field :title %></p>
    <p><%= t.label :details %></p>
    <p><%= t.text_field :details %></p>
    <%= t.label :completed %>
    <%= t.check_box :completed %>
    <p><%= t.submit %></p>
  <% end %>
</div>

app/views/tasks/list.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<h1> My Tasks </h1>
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <i class="fa fa-check-square-o"></i>
    <% else %>
      <i class="fa fa-square-o"></i>
    <% end %>
    <%= link_to task.title, task_path(task) %>
  <%end%>

<button type="button" class="btn btn-info"> <%= link_to 'Add a task', new_task_path %> </button>

app/views/tasks/new.html.erb
<div>
  <%= form_for(@task) do |t| %>
    <p><%= t.label :title %></p>
    <p><%= t.text_field :title %></p>
    <p><%= t.label :details %></p>
    <p><%= t.text_field :details %></p>
    <%= t.label :completed %>
    <%= t.check_box :completed %>
    <p><%= t.submit %></p>
  <% end %>
</div>